spring:
  application:
    name: last_service_oss

  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


#阿里云 OSS
#不同的服务器，地址不同
aliyun:
  oss:
    file:
      endPoInt: oss-cn-shanghai.aliyuncs.com
      keyId:
      keySecret:
      #bucket可以在控制台创建，也可以使用java代码创建
      bucketName: last-oss-picture