spring:
  application:
    name: last_service_edu

  profiles:
    active: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/last?serverTimezone=GMT%2B8
    username: root
    password: 981103
    hikari:
        connection-test-query: SELECT 1
        connection-timeout: 60000
        idle-timeout: 500000
        max-lifetime: 540000
        maximum-pool-size: 12
        minimum-idle: 10
        pool-name:  LastHikariPool
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:com/last/edu/mapper/xml/*.xml
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  type-aliases-package: com.last.edu.entity
logging:
  level:
    root: info
